EncyclopediaBundle\Entity\CharacterClass:
    type: entity
    table: null
    repositoryClass: EncyclopediaBundle\Repository\ClassRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        image:
            type: string
            length: 255
        exampleJobs:
            type: text
            column: example_jobs
        exampleActions:
            type: text
            column: example_actions
        description:
            type: text
    oneToMany:
        skills:
            targetEntity: EncyclopediaBundle\Entity\PassiveSkill
            mappedBy: class
    lifecycleCallbacks: {  }
