EncyclopediaBundle\Entity\Magic:
    type: entity
    table: null
    repositoryClass: EncyclopediaBundle\Repository\MagicRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
            nullable: false
        mpCost:
            type: integer
            column: mp_cost
            nullable: false
        duration:
            type: string
            length: 255
            nullable: false
        target:
            type: string
            length: 255
            nullable: false
        level:
            type: string
            length: 255
            nullable: false
        spellRange:
            type: string
            length: 255
            column: spell_range
            nullable: false
        castingTime:
            type: string
            length: 255
            column: casting_time
            nullable: false
        description:
            type: text
            nullable: false
        type:
            type: string
            length: 255
            nullable: false
    lifecycleCallbacks: {  }
