# docker-compose.yml
version: '3.3'

services:
  php:
    build:
      context: docker/php7-fpm
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ${SYMFONY_APP_PATH}:/var/www/app

  nginx:
    build:
      context: docker/nginx
    ports:
      - 80:80
    volumes:
      - ${SYMFONY_APP_PATH}:/var/www/app
      - ${SYMFONY_APP_PATH}/logs/nginx:/var/log/nginx/ryuutama
      - ${SYMFONY_APP_PATH}/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${SYMFONY_APP_PATH}/docker/nginx/sites-enabled:/etc/nginx/sites-enabled
    labels:
      fr.laposte.server.role: reserve-proxy

  mysql:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  adminer:
    image: adminer