EncyclopeadiaBundle\Entity\Magic:
    type: entity
    table: null
    repositoryClass: EncyclopeadiaBundle\Repository\MagicRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        mPCost:
            type: integer
            column: MP_Cost
        duration:
            type: string
            length: 255
        target:
            type: string
            length: 255
        level:
            type: string
            length: 255
        spellRange:
            type: string
            length: 255
            column: spell_range
        castingTime:
            type: string
            length: 255
            column: casting_time
        description:
            type: text
        type:
            type: string
            length: 255
    lifecycleCallbacks: {  }
