<?php

namespace EncyclopediaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MagicRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagicRepository extends EntityRepository
{
}
